### ISSUE TITLE
Unrecognized response class Insights

### ISSUE THREAD

**Issue by nicc** [Clarify/clarify-ruby#14]
Hi there,

I'm running into some troubles getting to Insights via the Ruby client.

My test is fairly simple:
```ruby
insights_url = bundle.relation('clarify:insights')
@clarify.get(insights_url).each do |insight|
  puts #{insight.inspect}
end
```

but when I run it I get:
```
Clarify::UnrecognizedResponseError: Unrecognized response class Insights
```

Here's the relevant part of the stack trace:
```
    from .../clarify-2.0.0/lib/clarify/response_factory.rb:14:in `rescue in make_result'
    from .../clarify-2.0.0/lib/clarify/response_factory.rb:7:in `make_result'
    from .../clarify-2.0.0/lib/clarify/rest_client.rb:113:in `make_result'
    from .../clarify-2.0.0/lib/clarify/rest_client.rb:97:in `request'
    from .../clarify-2.0.0/lib/clarify/rest_client.rb:27:in `get'
    from .../clarify-2.0.0/lib/clarify/client.rb:16:in `get'
```

I've gone digging, and the ``klass_for_class`` method in ```Clarify::ResponseFactory``` seems to be the culprit. There's no Insights key and corresponding class to handle that response type. I'm not too familiar with the response body that insights would generate, but the other response classes are fairly simple. Could we just add an Enumerable one similar to ```Clarify::Responses::Tracks```?

Let me know if you need any more info.

Nic

**Comment by grahamc** [comment]
Hi Nic,

It looks adding Insight support to the ruby library was an oversight. The good news is we're finalizing our schedule for the week, so I will put this as my first priority for the week.

Thank you for your report, I'll update the issue with a fix shortly.

Graham

**Comment by nicc** [comment]
Okay great.
Thanks for the quick response, Graham.

**Comment by grahamc** [comment]
@nicc After merging #15 this functionality should be complete. It will be v2.1.0 but I'm not able to push personally, but we will get this pushed to rubygems.org today.

**Comment by irothschild** [comment]
@nicc v2.1.0 has now been pushed!
